web_assignment_2020/web_assignment_2020/Models/FlightSchedule.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlTypes;

namespace web_assignment_2020.Models
{
    public class FlightSchedule
    {
        [Display(Name = "Schedule ID")]
        public int ScheduleID { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "Required, StringLength – cannot exceed 20 characters")]
        [Display(Name = "Flight Number")]
        public string FlightNumber { get; set; }

        [Required]
        [Display(Name = "Route ID")]
        public int RouteID { get; set; }

        [Display(Name = "Aircraft ID")]
        public int AircraftID { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        [Display(Name = "Departure DateTime")]
        public DateTime DepartureDateTime { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        [Display(Name = "Arrival DateTime")]
        public DateTime ArrivalDateTime { get; set; }

        [Required]
        [Display(Name ="Economy Class Price")]
        public decimal EconomyClassPrice { get; set; }

        [Required]
        [Display(Name = "Business Class Price")]
        public decimal BusinessClassPrice { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "Required, StringLength – cannot exceed 20 characters")]
        public string Status { get; set; }


        public FlightSchedule()
        {
            Status = "Opened";
        }
    }
}

web_assignment_2020/web_assignment_2020/Models/FlightScheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlTypes;

namespace web_assignment_2020.Models
{
    public class FlightScheduleViewModel
    {
        [Display(Name = "Schedule ID")]
        public int ScheduleID { get; set; }

        [Display(Name = "Flight Number")]
        public string FlightNumber { get; set; }

        [Display(Name = "Route ID")]
        public int RouteID { get; set; }

        [Display(Name = "Aircraft ID")]
        public int AircraftID { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Departure DateTime")]
        public DateTime DepartureDateTime { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Arrival DateTime")]
        public DateTime ArrivalDateTime { get; set; }

        [Display(Name = "Economy Class Price")]
        public decimal EconomyClassPrice { get; set; }

        [Display(Name = "Business Class Price")]
        public decimal BusinessClassPrice { get; set; }

        public string Status { get; set; }
    }
}

web_assignment_2020/web_assignment_2020/Controllers/FlightScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using web_assignment_2020.DAL;
using web_assignment_2020.Models;

namespace web_assignment_2020.Controllers
{
    public class FlightScheduleController : Controller
    {
        private List<string> statusList = new List<String> { "Opened", "Full", "Delayed", "Cancelled" };
        private FlightScheduleDAL flightScheduleContext = new FlightScheduleDAL();
        private FlightRouteDAL flightRouteContext = new FlightRouteDAL();
        

        // GET: FlightSchedule
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") == "Admin")
            {
                List<FlightSchedule> flightSchedules = flightScheduleContext.GetAllFlightSchedule();
                return View(flightSchedules);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: FlightSchedule/Details/5
        public ActionResult Details(int id)
        {
            ViewData["bookingList"] = flightScheduleContext.GetBooking(id);
            List<BookingViewModel> bookings = flightScheduleContext.GetBooking(id);
           
            return View(bookings);
        }

        // GET: FlightSchedule/Create
        public ActionResult Create()
        {
            ViewData["routeIDList"] = flightRouteContext.GetRouteIDs();
            ViewData["aircraftIDList"] = flightRouteContext.GetAircraftIDs();
            ViewData["statusList"] = statusList;

            return View();
        }

        // POST: FlightSchedule/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FlightSchedule flightSchedule)
        {
            //Get country list for drop-down list
            //in case of the need to return to Create.cshtml view
            ViewData["routeIDList"] = flightRouteContext.GetRouteIDs();
            ViewData["aircraftIDList"] = flightRouteContext.GetAircraftIDs();
            ViewData["statusList"] = statusList;

            if (ModelState.IsValid)
            {
                FlightRoute flightRoute = flightRouteContext.GetDetails(flightSchedule.RouteID);
                //Add staff record to database
                flightSchedule.ScheduleID = flightScheduleContext.Add(flightSchedule,flightRoute.FlightDuration);
                //Redirect user to Staff/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(flightSchedule);
            }
        }
        

        // GET: FlightSchedule/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewData["statusList"] = statusList;
            FlightSchedule flightSchedule = flightScheduleContext.GetDetails(id.Value);
            return View(flightSchedule);
        }

        // POST: FlightSchedule/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string status)
        {
            ViewData["statusList"] = statusList;
            /*if (ModelState.IsValid)
            {
                //Update staff record to database
                flightScheduleContext.Update(flightSchedule.ScheduleID,flightSchedule.Status);
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View("Index");
            }*/
            //Update staff record to database
            flightScheduleContext.Update(id.Value, status);
            return RedirectToAction("Index");
        }

        // GET: FlightSchedule/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FlightSchedule/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

web_assignment_2020/web_assignment_2020/Views/FlightSchedule/Create.cshtml
@model web_assignment_2020.Models.FlightSchedule

@{
    ViewData["Title"] = "Create";
}

<h4 class="PageTitle">Create Flight Schedule</h4>


<h4>FlightSchedule</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="FlightNumber" class="control-label"></label>
                <input asp-for="FlightNumber" class="form-control" />
                <span asp-validation-for="FlightNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RouteID" class="control-label"></label>
                <select asp-for="RouteID"
                        asp-items="@(new SelectList(
 @ViewData["routeIDList"] as List <int>))" class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="AircraftID" class="control-label"></label>
                <select asp-for="AircraftID"
                        asp-items="@(new SelectList(
 @ViewData["aircraftIDList"] as List <int>))" class="form-control"></select>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDateTime" class="control-label"></label>
                <input asp-for="DepartureDateTime" class="form-control"
                       min="@DateTime.Now.AddHours(24).ToString("yyyy-MM-ddTHH:mm")" />
                <span asp-validation-for="DepartureDateTime" class="text-danger"></span>
            </div>
            

            <div class="form-group">
                <label asp-for="EconomyClassPrice" class="control-label"></label>
                <input asp-for="EconomyClassPrice" class="form-control" />
                <span asp-validation-for="EconomyClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusinessClassPrice" class="control-label"></label>
                <input asp-for="BusinessClassPrice" class="form-control" />
                <span asp-validation-for="BusinessClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status"
                        asp-items="@(new SelectList(
 @ViewData["statusList"] as List <String>))" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web_assignment_2020/web_assignment_2020/Views/FlightSchedule/Details.cshtml
@model IEnumerable<web_assignment_2020.Models.BookingViewModel>

@{
    ViewData["Title"] = "Details";
}

<h4 class="PageTitle">Bookings of Schedule ID: @Html.Display("ScheduleID") </h4>


@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.BookingID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CustomerID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ScheduleID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PassengerName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PassportNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Nationality)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SeatClass)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.AmtPayable)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Remarks)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateTimeCreated)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.BookingID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CustomerID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ScheduleID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PassengerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PassportNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Nationality)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SeatClass)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.AmtPayable)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Remarks)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateTimeCreated)
                    </td>
                    
                </tr>
            }
        </tbody>
    </table>

}
else
{
    <h5  style="text-align: center;font-weight: bold;color: red;margin-top:250px;margin-bottom:250px;" >No bookings for selected flight schedule!</h5>
}

web_assignment_2020/web_assignment_2020/Views/FlightSchedule/Edit.cshtml
@model web_assignment_2020.Models.FlightSchedule

@{
    ViewData["Title"] = "Edit";
}

    <h4 class="PageTitle">Update Schedule ID: @Html.Display("ScheduleID") </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="ScheduleID" class="control-label"></label>
                <div class="form-control-plaintext">
                    @Html.Display("ScheduleID")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="FlightNumber" class="control-label"></label>
                <div class="form-control-plaintext">
                    @Html.Display("FlightNumber")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="RouteID" class="control-label"></label>
                <div class="form-control-plaintext">
                    @Html.Display("RouteID")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="AircraftID" class="control-label"></label>
                <div class="form-control-plaintext">
                    @Html.Display("AircraftID")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDateTime" class="control-label"></label>
                <div class="form-control-plaintext">
                    @Html.Display("DepartureDateTime")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalDateTime" class="control-label"></label>
                <div class="form-control-plaintext">
                    @Html.Display("ArrivalDateTime")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="EconomyClassPrice" class="control-label"></label>
                <div class="form-control-plaintext">
                    @Html.Display("EconomyClassPrice")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="BusinessClassPrice" class="control-label"></label>
                <div class="form-control-plaintext">
                    @Html.Display("BusinessClassPrice")
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status"
                        asp-items="@(new SelectList(
 @ViewData["statusList"] as List <String>))" class="form-control"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web_assignment_2020/web_assignment_2020/Views/FlightSchedule/Index.cshtml
@model IEnumerable<web_assignment_2020.Models.FlightSchedule>
@{
    ViewData["Title"] = "View Flight Schedule";
}
<h4 class="PageTitle">View Flight Schedule</h4>
<!-- Add a partial view to display a list of staff records
 in a tabular format. -->
<partial name="~/Views/FlightSchedule/_FlightScheduleView.cshtml" model="@Model" />

web_assignment_2020/web_assignment_2020/Views/FlightSchedule/_FlightScheduleView.cshtml
@model IEnumerable<web_assignment_2020.Models.FlightSchedule>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ScheduleID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RouteID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AircraftID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArrivalDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EconomyClassPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusinessClassPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ScheduleID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RouteID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AircraftID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArrivalDateTime)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.EconomyClassPrice)
            </td>
            <td>
                $@Html.DisplayFor(modelItem => item.BusinessClassPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="FlightSchedule"
                   asp-route-id="@item.ScheduleID">Update Status</a>
                <hr />
                <a asp-action="Details" asp-controller="FlightSchedule"
                   asp-route-id="@item.ScheduleID">Bookings</a>
            </td>
        </tr>
}
    </tbody>
</table>