web_assignment_2020/web_assignment_2020/Models/Aircraft.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace web_assignment_2020.Models
{
    public class Aircraft
    {
        [Display(Name = "ID")]
        public int AircraftID { get; set; }

        [Required(ErrorMessage = "Please Enter an Airplane Model!")]
        [Display(Name = "Model:")]
        public string MakeModel { get; set; }

        [Required(ErrorMessage = "Please specify Number of Seats!")]
        [Display(Name = "Economy Seats:")]
        public int? NumEconomySeat { get; set; }

        [Required(ErrorMessage = "Please specify Number of Seats!")]
        [Display(Name = "Business Seats:")]
        public int? NumBusinessSeat { get; set; }

        [Required(ErrorMessage = "Please enter a date")]
        [Display(Name = "Date of Last Maintenace:")]
        [DataType(DataType.DateTime)]
        public DateTime DLM { get; set; }

        [Display(Name = "Aircraft Status:")]
        public string Status { get; set; }

        public Aircraft()
        {
            Status = "Operational";
        }
    }
}

web_assignment_2020/web_assignment_2020/Models/AssignAircraft.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace web_assignment_2020.Models
{
    public class AssignAircraft : Aircraft
    {
        [Display(Name = "ScheduleID")]
        public int ScheduleID { get; set; }
    }
}

web_assignment_2020/web_assignment_2020/Models/FlightSchedule.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlTypes;

namespace web_assignment_2020.Models
{
    public class FlightSchedule
    {
        [Display(Name = "Schedule ID")]
        public int ScheduleID { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "Required, StringLength – cannot exceed 20 characters")]
        [Display(Name = "Flight Number")]
        public string FlightNumber { get; set; }

        [Required]
        [Display(Name = "Route ID")]
        public int RouteID { get; set; }

        [Display(Name = "Aircraft ID")]
        public int AircraftID { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        [Display(Name = "Departure DateTime")]
        public DateTime DepartureDateTime { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        [Display(Name = "Arrival DateTime")]
        public DateTime ArrivalDateTime { get; set; }

        [Required]
        [Display(Name ="Economy Class Price")]
        public decimal EconomyClassPrice { get; set; }

        [Required]
        [Display(Name = "Business Class Price")]
        public decimal BusinessClassPrice { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = "Required, StringLength – cannot exceed 20 characters")]
        public string Status { get; set; }


        public FlightSchedule()
        {
            Status = "Opened";
        }
    }
}

web_assignment_2020/web_assignment_2020/Models/FlightScheduleViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.Data.SqlTypes;

namespace web_assignment_2020.Models
{
    public class FlightScheduleViewModel
    {
        [Display(Name = "Schedule ID")]
        public int ScheduleID { get; set; }

        [Display(Name = "Flight Number")]
        public string FlightNumber { get; set; }

        [Display(Name = "Route ID")]
        public int RouteID { get; set; }

        [Display(Name = "Aircraft ID")]
        public int AircraftID { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Departure DateTime")]
        public DateTime DepartureDateTime { get; set; }

        [DataType(DataType.DateTime)]
        [Display(Name = "Arrival DateTime")]
        public DateTime ArrivalDateTime { get; set; }

        [Display(Name = "Economy Class Price")]
        public decimal EconomyClassPrice { get; set; }

        [Display(Name = "Business Class Price")]
        public decimal BusinessClassPrice { get; set; }

        public string Status { get; set; }
    }
}

web_assignment_2020/web_assignment_2020/Controllers/AircraftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using web_assignment_2020.DAL;
using web_assignment_2020.Models;

namespace web_assignment_2020.Controllers
{
    public class AircraftController : Controller
    {
        private List<string> availabilityList = new List<String> { "Operational", "Under Maintenance" };
        private AircraftDAL aircraftContext = new AircraftDAL();
        

        // GET: Aircraft
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") == "Admin")
            {
                List<Aircraft> aircraftList = aircraftContext.GetAircraft();
                return View(aircraftList);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: Aircraft/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Aircraft/Create
        public ActionResult Create()
        {
            ViewData["availabilityList"] = availabilityList;
            return View();
        }

        // POST: Aircraft/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Aircraft aircraft)
        {
            if (ModelState.IsValid)
            {
                aircraft.AircraftID = aircraftContext.Add(aircraft);
                return RedirectToAction("Index");
            }
            else
            {
                return View(aircraft);
            }
        }

        // POST: Aircraft/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Aircraft aircraft)
        {
            if (ModelState.IsValid)
            {
                aircraftContext.Update(aircraft);
                return RedirectToAction("Index");
            }
            else
            {
                return View(aircraft);
            }
        }

        public IActionResult Edit(int? id)
        {
            if (id != null)
            {
                List<Aircraft> aircraftList;
                aircraftList = aircraftContext.GetAircraft();
                foreach (Aircraft a in aircraftList)
                {
                    if (a.AircraftID == id)
                    {
                        ViewData["availabilityList"] = availabilityList;
                        return View(a);
                    }
                }
            }
            return RedirectToAction("_AircraftView");
        }

        // GET: Aircraft/Delete/5
        public ActionResult Delete(int id)
        {
            Aircraft aircraft = aircraftContext.GetDetails(id);
            return View(aircraft);
        }

        // POST: Aircraft/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Aircraft aircraft)
        {
            // Delete the staff record from database
            aircraftContext.Delete(aircraft.AircraftID);

            return RedirectToAction("Index");

        }

        // View of All Flight Schedules
        public IActionResult FlightScheduleView()
        {
            if (HttpContext.Session.GetString("Role") == "Admin")
            {
                List<FlightSchedule> flightSchedule = aircraftContext.GetAllFlightSchedule();
                return View(flightSchedule);
            }
            else
            {   
                return RedirectToAction("Index", "Home");
            }
        }

        // Select Aircraft to set to a certain Flight Schedule
        public ActionResult AssignAircraft(int? id)
        {
            if (id == null)
            { //Query string parameter not provided
              //Return to listing page, not allowed to edit
                return RedirectToAction("Create");
            }
            FlightSchedule flightSchedule = aircraftContext.GetFlightSchedules(id.Value);

            ViewData["aircraftIDs"] = aircraftContext.GetAllAircraftID();

            if (flightSchedule == null)
            {
                //Return to listing page, not allowed to edit
                return RedirectToAction("Index");
            }
            
            return View(flightSchedule);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AssignAircraft(FlightSchedule flightSchedule)
        {
            if (ModelState.IsValid)
            {
                ViewData["aircraftIDs"] = aircraftContext.GetAllAircraftID();
                aircraftContext.AssignAircraft(flightSchedule);
                return RedirectToAction("FlightScheduleView");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View(flightSchedule);
            }
        }

    }
}

web_assignment_2020/web_assignment_2020/Controllers/FlightScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using web_assignment_2020.DAL;
using web_assignment_2020.Models;

namespace web_assignment_2020.Controllers
{
    public class FlightScheduleController : Controller
    {
        private List<string> statusList = new List<String> { "Opened", "Full", "Delayed", "Cancelled" };
        private FlightScheduleDAL flightScheduleContext = new FlightScheduleDAL();
        private FlightRouteDAL flightRouteContext = new FlightRouteDAL();
        

        // GET: FlightSchedule
        public ActionResult Index()
        {
            if (HttpContext.Session.GetString("Role") == "Admin")
            {
                List<FlightSchedule> flightSchedules = flightScheduleContext.GetAllFlightSchedule();
                return View(flightSchedules);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // GET: FlightSchedule/Details/5
        public ActionResult Details(int id)
        {
            ViewData["bookingList"] = flightScheduleContext.GetBooking(id);
            List<BookingViewModel> bookings = flightScheduleContext.GetBooking(id);
           
            return View(bookings);
        }

        // GET: FlightSchedule/Create
        public ActionResult Create()
        {
            ViewData["routeIDList"] = flightRouteContext.GetRouteIDs();
            ViewData["aircraftIDList"] = flightRouteContext.GetAircraftIDs();
            ViewData["statusList"] = statusList;

            return View();
        }

        // POST: FlightSchedule/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FlightSchedule flightSchedule)
        {
            //Get country list for drop-down list
            //in case of the need to return to Create.cshtml view
            ViewData["routeIDList"] = flightRouteContext.GetRouteIDs();
            ViewData["aircraftIDList"] = flightRouteContext.GetAircraftIDs();
            ViewData["statusList"] = statusList;

            if (ModelState.IsValid)
            {
                FlightRoute flightRoute = flightRouteContext.GetDetails(flightSchedule.RouteID);
                //Add staff record to database
                flightSchedule.ScheduleID = flightScheduleContext.Add(flightSchedule,flightRoute.FlightDuration);
                //Redirect user to Staff/Index view
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the Create view
                //to display error message
                return View(flightSchedule);
            }
        }
        

        // GET: FlightSchedule/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewData["statusList"] = statusList;
            FlightSchedule flightSchedule = flightScheduleContext.GetDetails(id.Value);
            return View(flightSchedule);
        }

        // POST: FlightSchedule/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int? id, string status)
        {
            ViewData["statusList"] = statusList;
            /*if (ModelState.IsValid)
            {
                //Update staff record to database
                flightScheduleContext.Update(flightSchedule.ScheduleID,flightSchedule.Status);
                return RedirectToAction("Index");
            }
            else
            {
                //Input validation fails, return to the view
                //to display error message
                return View("Index");
            }*/
            //Update staff record to database
            flightScheduleContext.Update(id.Value, status);
            return RedirectToAction("Index");
        }

        // GET: FlightSchedule/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FlightSchedule/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

web_assignment_2020/web_assignment_2020/Views/Aircraft/AssignAircraft.cshtml
@model web_assignment_2020.Models.FlightSchedule

@{
    ViewData["Title"] = "AssignAircraft";
}

<h4 class="PageTitle">Assign Aircraft to Flight Schedule: <u>@Html.Display("ScheduleID")</u></h4>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AssignAircraft">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
               <label asp-for="AircraftID" class="control-label"> Aircraft IDs that are <u><b>Operational:</b></u></label>
                <select asp-for="AircraftID" 
                        asp-items="@( new SelectList(
                        @ViewData["aircraftIDs"] as List <int>))" class="form-control"></select>
                <span asp-validation-for="AircraftID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ScheduleID" class="control-label"> Selected Schedule ID:</label>
                <input asp-for="ScheduleID" class="form-control"readonly />
                <span asp-validation-for="ScheduleID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FlightNumber" class="control-label"> Flight Number:</label>
                <input asp-for="FlightNumber" class="form-control"readonly />
                <span asp-validation-for="FlightNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RouteID" class="control-label"> Route ID:</label>
                <input asp-for="RouteID" class="form-control"readonly />
                <span asp-validation-for="RouteID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DepartureDateTime" class="control-label"> Departure Date & Time:</label>
                <input asp-for="DepartureDateTime" class="form-control"readonly />
                <span asp-validation-for="DepartureDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArrivalDateTime" class="control-label"> Arrival Date & Time:</label>
                <input asp-for="ArrivalDateTime" class="form-control"readonly />
                <span asp-validation-for="ArrivalDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EconomyClassPrice" class="control-label"> Economy Class ($):</label>
                <input asp-for="EconomyClassPrice" class="form-control"readonly />
                <span asp-validation-for="EconomyClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BusinessClassPrice" class="control-label"> Business Class ($):</label>
                <input asp-for="BusinessClassPrice" class="form-control"readonly />
                <span asp-validation-for="BusinessClassPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"> Flight Schedule Status:</label>
                <input asp-for="Status" class="form-control"readonly />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Assign" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

web_assignment_2020/web_assignment_2020/Views/Aircraft/Create.cshtml
@model web_assignment_2020.Models.Aircraft

@{
    ViewData["Title"] = "Create";
}

<h4 class="PageTitle">Create Aircraft Record</h4>
<br />
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MakeModel" class="control-label"></label>
                <input asp-for="MakeModel" class="form-control" />
                <span asp-validation-for="MakeModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumEconomySeat" class="control-label"></label>
                <input asp-for="NumEconomySeat" class="form-control" />
                <span asp-validation-for="NumEconomySeat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumBusinessSeat" class="control-label"></label>
                <input asp-for="NumBusinessSeat" class="form-control" />
                <span asp-validation-for="NumBusinessSeat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DLM" class="control-label"></label>
                <input asp-for="DLM" class="form-control" />
                <span asp-validation-for="DLM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select class="form-control" id="Status" name="Status">
                    <option>Operational</option>
                </select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Aircraft" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">View All Aircraft Records</a>
</div>
<br>

web_assignment_2020/web_assignment_2020/Views/Aircraft/Delete.cshtml
@model web_assignment_2020.Models.Aircraft

@{
    ViewData["Title"] = "Delete";
}

<h4 class="PageTitle">Delete Aircraft Record</h4>

<h5>Are you sure you want to delete this?</h5>
    
<form asp-action="Delete">
    <fieldset class="FormContent">
        <div class="form-group row">
            <label asp-for="AircraftID"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="AircraftID" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="MakeModel"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-5">
                <input asp-for="MakeModel" readonly
                       class="form-control-plaintext" />
            </div>
        </div>

        <input type="submit" value="Delete" class="btn btn-danger" />
        <hr />
        <div>
            <a asp-action="Index">Back to List</a>
        </div>
    </fieldset>
</form>

web_assignment_2020/web_assignment_2020/Views/Aircraft/Details.cshtml
@model web_assignment_2020.Models.Aircraft

@{
    ViewData["Title"] = "Details";
}

<h4 class="PageTitle">Aircraft Details</h4>

<div>
    <h4>Aircraft</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AircraftID)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AircraftID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MakeModel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MakeModel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumEconomySeat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumEconomySeat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumBusinessSeat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumBusinessSeat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DLM)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DLM)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

web_assignment_2020/web_assignment_2020/Views/Aircraft/Edit.cshtml
@model web_assignment_2020.Models.Aircraft

@{
    ViewData["Title"] = "Edit";
}

    <h4 class="PageTitle">Update Aircraft Status</h4>

<h4>Aircraft</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AircraftID" class="control-label"></label>
                <input asp-for="AircraftID" class="form-control" readonly/>
                <span asp-validation-for="AircraftID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MakeModel" class="control-label"></label>
                <input asp-for="MakeModel" class="form-control" readonly/>
                <span asp-validation-for="MakeModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumEconomySeat" class="control-label"></label>
                <input asp-for="NumEconomySeat" class="form-control" readonly/>
                <span asp-validation-for="NumEconomySeat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumBusinessSeat" class="control-label"></label>
                <input asp-for="NumBusinessSeat" class="form-control" readonly/>
                <span asp-validation-for="NumBusinessSeat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DLM" class="control-label"></label>
                <input asp-for="DLM" class="form-control" readonly/>
                <span asp-validation-for="DLM" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status"
                        asp-items="@(new SelectList(
 @ViewData["availabilityList"] as List<String>))" class="form-control"></select>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back To List Of Aircraft</a>
</div>

web_assignment_2020/web_assignment_2020/Views/Aircraft/FlightScheduleView.cshtml
@model IEnumerable<web_assignment_2020.Models.FlightSchedule>

@{
    ViewData["Title"] = "FlightScheduleView";
}

<h4 class="PageTitle">Assign Aircraft to Flight Schedule</h4>
<br />
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ScheduleID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FlightNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RouteID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AircraftID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DepartureDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ArrivalDateTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EconomyClassPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BusinessClassPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ScheduleID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FlightNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RouteID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AircraftID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DepartureDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ArrivalDateTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EconomyClassPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BusinessClassPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="AssignAircraft" asp-controller="Aircraft"
                   asp-route-id="@item.ScheduleID">Assign Aircraft</a>
            </td>
        </tr>
}
    </tbody>
</table>

web_assignment_2020/web_assignment_2020/Views/Aircraft/Index.cshtml
@model IEnumerable<web_assignment_2020.Models.Aircraft>
@{
    ViewData["Title"] = "Index";
}

<h4 class="PageTitle">View All Registered Aircraft</h4>

<partial name="~/Views/Aircraft/_AircraftView.cshtml" model="@Model" />

web_assignment_2020/web_assignment_2020/Views/Aircraft/_AircraftView.cshtml
@model IEnumerable<web_assignment_2020.Models.Aircraft>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.AircraftID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MakeModel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumEconomySeat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumBusinessSeat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DLM)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AircraftID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MakeModel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumEconomySeat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumBusinessSeat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DLM)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="Aircraft" asp-route-id="@item.AircraftID">Update Aircraft Status</a>
                |
                <a asp-action="Delete" asp-controller="Aircraft" asp-route-id="@item.AircraftID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>